### ISSUE TITLE
Change TOC font-weight based on paragraph level

### ISSUE THREAD

**Issue by atteggiani** [ACCESS-NRI/ACCESS-Hive-Docs#897]
## Overview

To improve readability of the Table of Content (TOC) on the right side of the website, the font-weight should be changed depending on the paragraph heading level (`#` (`h1`),`##` (`h2`) `###` (`h3`), etc.), in a descending fashion:

Something like:
```css
.h1-toc-item {
    font-weight: 600;
}
.h2-toc-item {
    font-weight: 400;
}
.h3-toc-item {
    font-weight: 200;
}
...
```

> [!IMPORTANT]
> The class names above are only used as an example and don't reflect the actual class names that need to be used to achieve the task.
